### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by RomanJos** [TobiasHu2021/vscode-scp#2]
Hello, love the extension.

I don't know if its known or anything but I didn't find anything on the readme. I had to reload in order for the extension to find the json files and needed to `ln /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass` on Arch linux.
I believe those steps should be indicated in the readme.

Thank you for your works

Edit : Just found out that editing a file outside of my workspace trigger the extension too

**Comment by ethan-phu** [comment]
> Hello, love the extension.
> 
> I don't know if its known or anything but I didn't find anything on the readme. I had to reload in order for the extension to find the json files and needed to `ln /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass` on Arch linux. I believe those steps should be indicated in the readme.
> 
> Thank you for your works
> 
> Edit : Just found out that editing a file outside of my workspace trigger the extension too

Thanks for your feedback, I will take care of this issue in the next release. Regarding this issue that I need more detailed information about `ln /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass`, to fix this bug, would you be comfortable providing it?

**Comment by RomanJos** [comment]
Awesome, my symlink is a workaround currently and would't be suited for most users, I believe the best way would be to mimic the [behavior](https://code.visualstudio.com/docs/remote/ssh#_remember-hosts-and-advanced-settings) of the Microsoft ssh extension. It ask a command or a host, the ssh config file to save changes (or to read already saved host by the user or the extension) and then ask for the password if its needed for the host or the passphrase or whatever.
This way no additional dependencies would be needed and everything would stay inside the vscode window.

I tried to look for the source code of the microsoft extension but couldn't find it for some reasons so you may need to implement it from scratch :(

**Comment by ethan-phu** [comment]
Hello, happy new year, the latest version of the plugin has been released. In the latest version, we support the configuration of the private key address by adding new configuration items

**Comment by RomanJos** [comment]
Hello, haven't checked in a while, thank you really much for your work ! I wish you a happy new year too, or perhaps, rest of the year ;)
