### ISSUE TITLE
执行 >vscode-scp: Local->Rmote 出错 : Cannot read properties of undefined (reading 'cfpath')

### ISSUE THREAD

**Issue by ycMia** [TobiasHu2021/vscode-scp#4]
您好Ethan,
这是一个很好立意的软件, 然而我在windows10上无法使用它

配置`.vscode/scp.json`生成成功, 然而
插件无法运行, 其报错信息为: `Cannot read properties of undefined (reading 'cfpath')` 于visual studio code 中, 在每次执行 `>vscode-scp: Local->Rmote`时

我的json文件形如:
```
{
    "host": "*.*.*.*",
    "port": 22,
    "user": "root",
    "ignore":[".git",".vscode"],
    "remotePath": "/var/www/html",
    "uploadOnSave": true
}
```
同时已经确认远端已上传公钥并且可在shell中登录
我使用 windows10 22H2版本, vscode使用1.73.1
请问我将如何配置可使该插件运行? 谢谢

**Comment by ethan-phu** [comment]
重启一下vscode?还会不会出现呢？

**Comment by ycMia** [comment]
重启后报
`Cannot read properties of undefined (reading 'remotePath')`
错误

目前未找到其它报错信息

在客户端使用scp呼唤, 可用终端进行scp传输(读/写)文件; 服务器使用密钥登录, 非密码形式

**Comment by ethan-phu** [comment]
需要配置目的地址

**Comment by ycMia** [comment]
额...有点不明白...
请问目的地址是否是"remotePath" ? 我将其设置为"/var/www/html" , 认为这是一个合法的地址格式

**Comment by ethan-phu** [comment]
在最新版的插件中已经修复了该问题，你可以验证下

**Comment by ycMia** [comment]
该问题已修复, 感谢支持!
